### ISSUE TITLE
JSONUtil.parseObj问题

### ISSUE THREAD

**Issue by dreamToLongdaliang** [looly/hutool-site#3]
测试demo:
        String str = "{aaz217:100000054128897953e4}";
        System.out.println(JSONUtil.parseObj(str));

输出：
{"aaz217":1.0000005412889795E21}

原因可能是类型溢出，是不是要增加个处理。

**Comment by looly** [comment]
这个没问题。

`100000054128897953e4`这样的数字远大于long的范围，因此Hutool默认使用`BigDecimal`处理，再转String就是`BigDecimal`的toString形式，是科学计数法.

最新版本默认输出非科学计数法形式：

```java
String str = "{\"test\":100000054128897953e4}";
Console.log(JSONUtil.parseObj(str));
// {"test":1000000541288979530000}
```

**Comment by dreamToLongdaliang** [comment]
好的，感谢您的解答，祝Hutool越来越棒。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "looly/hutool-site"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月16日(星期三) 晚上10:55
***@***.***&gt;;
抄送:&nbsp;"wo ***@***.******@***.***&gt;;
主题:&nbsp;Re: [looly/hutool-site] JSONUtil.parseObj问题 (#3)





 
这个没问题。
 
100000054128897953e4这样的数字远大于long的范围，因此Hutool默认使用BigDecimal处理，再转String就是BigDecimal的toString形式，是科学计数法.
 
最新版本默认输出非科学计数法形式：
 String str = "{\"test\":100000054128897953e4}"; Console.log(JSONUtil.parseObj(str)); // {"test":1000000541288979530000}
