### ISSUE TITLE
查看文档时，滚动文档内容左侧的大纲也会一起滚动

### ISSUE THREAD

**Issue by zhj9709** [looly/hutool-site#6]
目前在文档中滚动时，大纲也会滚动，正在读的章节(标题)会滚动到大纲的最下面，体验不是很好。每次看完当前的内容，还需要在大纲那里滚动一下，看下面的内容。

![image](https://user-images.githubusercontent.com/13991774/184540416-efd1fe41-6415-4e81-975e-3041586c0d07.png)
![image](https://user-images.githubusercontent.com/13991774/184540423-36dd21f7-1af3-4d98-894d-af9a99332d86.png)

**Comment by looly** [comment]
这是docsify的问题，后续会使用新的文档系统。
