### ISSUE TITLE
java.lang.NoSuchMethodError: cn.hutool.core.util.ObjectUtil.defaultIfNull(Ljava/lang/Object;Ljava/util/function/Supplier;)Ljava/lang/Object;

### ISSUE THREAD

**Issue by yizdream** [looly/hutool-site#9]
[系统异常]Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: cn.hutool.core.util.ObjectUtil.defaultIfNull(Ljava/lang/Object;Ljava/util/function/Supplier;)Ljava/lang/Object;
报错的地方：  return new JSONObject(obj, (JSONConfig)ObjectUtil.defaultIfNull(config, JSONConfig::create));
![image](https://github.com/looly/hutool-site/assets/120292779/815e9cad-56b7-4ab9-9da3-140a94551910)

**Comment by looly** [comment]
版本冲突了。
